version: "3.8"
services:
    vote:
        ports:
            - 5000:80
        container_name: vote
        volumes:
            - vote:/app
        networks:
            - frontend
            - backend
        image: vote
    result:
        container_name: result
        ports:
            - 5001:80
        networks:
            - frontend
            - backend
        volumes:
            - result:/app
        image: result
    worker:
        container_name: worker
        networks:
            - backend
        image: worker
    redis:
        container_name: redis
        networks:
            - backend
        image: redis
    db:
        container_name: db
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        networks:
            - backend
        volumes:
            - db:/var/lib/postgresql/data
        image: postgres
networks:
    frontend:
    backend:
volumes:
    vote:
    result:
    db: